version: "3.0"
services:
  consul:
    image: consul:1.6.1
    container_name: consul
    restart: no
    ports:
    - 8500:8500
    command: agent -server -bind=127.0.0.1 -ui -bootstrap-expect=1 -client=0.0.0.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
