version: "3.0"

services:
  elastic_search:
    build:
      context: .
      dockerfile: ./conf/elasticsearch.dockerfile
    container_name: es
    environment:
    - discovery.type=single-node
    - ES_CLUSTERNAME=docker-cluster
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
    - es-data:/usr/share/elasticsearch/data
    - es-config:/usr/share/elasticsearch/config  #分词器的配置在config目录下
    - es-logs:/usr/share/elasticsearch/logs
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "9200:9200"
    - "9300:9300"
    restart: "no"
  kibana:
    image: kibana:7.5.2
    container_name: kibana
    environment:
      SERVER_NAME: es:9200
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
    - "5601:5601"
    restart: "no"
  logstash:
    image: logstash:7.14.0
    container_name: logstash
    restart: always
    volumes:
      - /home/hujian/logstash-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:rw
      - /home/hujian/logstash-config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - logstash-data:/usr/share/logstash/data/movies.csv
    depends_on:
      - elastic_search
    ports:
      - "4560:4560"
  nginx:
    image: nginx:1.10
    container_name: nginx
    volumes:
    - es-nx-html:/usr/share/nginx/html
    - es-nx-conf:/etc/nginx
    - es-nx-logs:/var/log/nginx
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "80:80"
    restart: "no"
volumes:
  es-data:
  es-plugins:
  es-logs:
  es-config:
  logstash-data:
  es-nx-html:
  es-nx-conf:
  es-nx-logs: