version: "3.0"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: jenkins
    volumes:
    - jenkins-info:/var/jenkins_home #数据文件挂载
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "90:8080"
    - "50000:50000"
    restart: "no"
volumes:
  jenkins-info: