version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongo
    restart: "no"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - db:/data/db
    - log:/var/log/mongodb
    - config:/etc/mongo
    ports:
    - "27017:27017"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: "no"
    ports:
    - "8081:8081"
    volumes:
    - /etc/localtime:/etc/localtime:ro
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    depends_on:
      - mongo
volumes:
  db:
  log:
  config: