version: "3"
services:
  nacos1:
    hostname: nacos1
    container_name: nacos1
    image: nacos/nacos-server:2.0.1
    volumes:
    - nacos1-log:/home/nacos/logs
    - ./dc-nacos-conf.properties:/home/nacos/init.d/custom.properties
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "8848:8848"
    - "9848:9848"
    - "9555:9555"
    environment:
      PREFER_HOST_MODE: hostname
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_cluster
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 256m
    restart: always
    networks:
    - dc
  nacos2:
    hostname: nacos2
    image: nacos/nacos-server:2.0.1
    container_name: nacos2
    volumes:
    - nacos2-log:/home/nacos/logs
    - ./dc-nacos-conf.properties:/home/nacos/init.d/custom.properties
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "8849:8848"
    - "9849:9848"
    environment:
      PREFER_HOST_MODE: hostname
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_cluster
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 256m
    restart: always
    networks:
    - dc
  nacos3:
    hostname: nacos3
    image: nacos/nacos-server:2.0.1
    container_name: nacos3
    volumes:
    - nacos3-log:/home/nacos/logs
    - ./dc-nacos-conf.properties:/home/nacos/init.d/custom.properties
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "8850:8848"
    - "9850:9848"
    environment:
      PREFER_HOST_MODE: hostname
      NACOS_SERVERS: nacos1:8848 nacos2:8848 nacos3:8848
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_cluster
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 256m
    restart: always
    networks:
    - dc
volumes:
  nacos1-log:
  nacos2-log:
  nacos3-log:
networks:
  dc: