version: "3"
services:
  nacos:
    hostname: nacos
    container_name: nacos
    image: nacos/nacos-server:2.0.1
    volumes:
    - nacos-log:/home/nacos/logs
    - ./dc-nacos-conf.properties:/home/nacos/init.d/custom.properties
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "8848:8848"
    - "9848:9848"
    - "9555:9555"
    environment:
      PREFER_HOST_MODE: hostname
      MODE: standalone
      MYSQL_SERVICE_HOST: mysql
      MYSQL_SERVICE_DB_NAME: nacos_cluster
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: root
      MYSQL_SERVICE_PASSWORD: root
      JVM_XMS: 256m
      JVM_XMX: 256m
      JVM_XMN: 256m
    restart: always
    networks:
    - dc
volumes:
  nacos-log:
networks:
  dc: