version: "3.0"

services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    ports:
    - "9000:9000"
    volumes:
    - portainer-data:/data
    - /var/run/docker.sock:/var/run/docker.sock
volumes:
  portainer-data:
