version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: no
    hostname: myRabbitmq
    ports:
    - 15672:15672
    - 5672:5672
    volumes:
    - rabbitmq-data:/var/lib/rabbitmq
    - /etc/localtime:/etc/localtime:ro
    environment:
    - RABBITMQ_DEFAULT_USER=root
    - RABBITMQ_DEFAULT_PASS=root
volumes:
  rabbitmq-data: