version: "3.0"

services:
  redis:
    image: redis:5.0.10
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
    - redis-data:/data #数据文件挂载
    - /etc/localtime:/etc/localtime:ro
    ports:
    - "6379:6379"
    restart: "no"
volumes:
  redis-data: