version: "3.0"

services:

  seata-server:
    container_name: seata
    image: seataio/seata-server:1.4.2
    hostname: seata-server
    ports:
    - 8091:8091
    environment:
    - SEATA_PORT=8091
    - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    expose:
    - 8091
    volumes:
    - ./conf/seata-config:/root/seata-config
    networks:
    - dc
networks:
  dc: